Make plugin no longer self registering
chartjs/chartjs-plugin-deferred pull request #24
Opened 2022-01-30 18:54 UTC by LeeLenaleee

Working example: https://codepen.io/leelenaleee/pen/ExwBJgK

2022-01-30 19:19 UTC, simonbrunel requested changes
Awesome! Strange that you didn't have to change the plugin integration in the docs. Not sure why it was already [integrated that way](https://github.com/chartjs/chartjs-plugin-deferred/blob/master/docs/scripts/register.js#L5).

Can you also add a migration page, similar to [this one](https://github.com/chartjs/chartjs-plugin-datalabels/blob/master/docs/guide/migration.md#migration)? (mostly a copy/paste and remove parts that doesn't apply to this plugin).

2022-01-30 19:19 UTC, simonbrunel commented on docs/guide/getting-started.md
> +# Getting started
nit: `Getting Started` (uppercase S)

2022-01-30 19:19 UTC, simonbrunel commented on docs/guide/getting-started.md
> +# Getting started
The link in [guide/README.md file](https://github.com/chartjs/chartjs-plugin-deferred/blob/master/docs/guide/README.md#table-of-contents) needs to be renamed and updated. Same in the [root README.md](https://github.com/chartjs/chartjs-plugin-deferred#documentation).

2022-01-30 19:19 UTC, simonbrunel commented on docs/guide/getting-started.md
> +import ChartDeferred from 'chartjs-plugin-datalabels';
typo: `chartjs-plugin-deferred` instead of `chartjs-plugin-datalabels`.

2022-02-03 07:34 UTC, simonbrunel approved these changes
Thanks a lot @LeeLenaleee!

2022-02-03 07:37 UTC, merged

2022-02-03 09:22 UTC, gregh3269 commented
Hello,
I have retested this and now for me it does not load deferred.  I use the html  version, and at the moment I am using

```
new Chart(..
plugins: {
            deferred: {
              xOffset: 150,   ## defer until 150px of the canvas width are inside the viewport
              yOffset: '50%', ## defer until 50% of the canvas height are inside the viewport
              delay: 500      ## delay of 500 ms after the canvas is considered inside the viewport
            }
          }
...
```
as in the read me.  Do I have to change anything here?

The docs now mention this:
```
var chart = new Chart(ctx, {
  plugins: [ChartDeferred],
  options: {
    // ...
  }
})
```

2022-02-03 09:47 UTC, LeeLenaleee commented
@gregh3269 do you have a reproducible sample because when I tested this it worked fine: https://codepen.io/leelenaleee/pen/ExwBJgK

2022-02-03 09:55 UTC, gregh3269 commented
Ok, I can see we now must have a

Chart.register(ChartDeferred);

first, which makes a global, guess we now cannot do it inline ?

from the getting started what does this mean/do then?

OR only to specific charts
```
var chart = new Chart(ctx, {
  plugins: [ChartDeferred],
  options: {
    // ...
  }
})
```

2022-02-03 11:06 UTC, LeeLenaleee commented
@gregh3269 mb, seems I forgot to save the pen, updated it with inline register and it seems to work fine so if it is not working please share a sample of it: https://codepen.io/leelenaleee/pen/ExwBJgK

2022-02-03 11:17 UTC, gregh3269 commented
ok thanks, makes sense now!

```javascript
new Chart(...
  plugins: [ChartDeferred],
  ...
  options: {
    ...
    plugins: {
      deferred: {
        xOffset: 150,   ## defer until 150px of the canvas width are inside the viewport
        yOffset: '50%', ## defer until 50% of the canvas height are inside the viewport
        delay: 500      ## delay of 500 ms after the canvas is considered inside the viewport
      }
    }
  }
});
```